apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dekt-apps

resources:
  - dekt4pets-backend.yaml
  - routes/dekt4pets-backend-route-config.yaml
  - routes/dekt4pets-backend-mapping.yaml
  
