apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: gateway-demo
spec:
  ssoEnabled: true
  routes:
    - id: animal-rescue-frontend
      uri: http://animal-rescue-frontend.animal-rescue.svc.cluster.local
      predicates:
        - Path=/rescue/**
      filters:
        - StripPrefix=1
    - id: animal-rescue-backend
      uri: http://animal-rescue-backend.animal-rescue.svc.cluster.local
      ssoEnabled: false
      predicates:
        - Path=/api/**
      filters:
        - StripPrefix=1
